package bean;
// Generated 19-Feb-2017 19:06:23 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Festival generated by hbm2java
 */
public class Festival  implements java.io.Serializable {


     private String naziv;
     private Date vremeOd;
     private Date vremeDo;
     private String mesto;
     private int brUlaznica;
     private int cenaZaDan;
     private int canaZaPaket;
     private int ocena;
     private int maxKarata;
     private int maxDnevno;
     private String poDanima;
     private Set<Galerija> galerijas = new HashSet<Galerija>(0);

    public Festival() {
    }

	
    public Festival(String naziv, Date vremeOd, Date vremeDo, String mesto, int brUlaznica, int cenaZaDan, int canaZaPaket, int ocena, int maxKarata, int maxDnevno, String poDanima) {
        this.naziv = naziv;
        this.vremeOd = vremeOd;
        this.vremeDo = vremeDo;
        this.mesto = mesto;
        this.brUlaznica = brUlaznica;
        this.cenaZaDan = cenaZaDan;
        this.canaZaPaket = canaZaPaket;
        this.ocena = ocena;
        this.maxKarata = maxKarata;
        this.maxDnevno = maxDnevno;
        this.poDanima = poDanima;
    }
    public Festival(String naziv, Date vremeOd, Date vremeDo, String mesto, int brUlaznica, int cenaZaDan, int canaZaPaket, int ocena, int maxKarata, int maxDnevno, String poDanima, Set<Galerija> galerijas) {
       this.naziv = naziv;
       this.vremeOd = vremeOd;
       this.vremeDo = vremeDo;
       this.mesto = mesto;
       this.brUlaznica = brUlaznica;
       this.cenaZaDan = cenaZaDan;
       this.canaZaPaket = canaZaPaket;
       this.ocena = ocena;
       this.maxKarata = maxKarata;
       this.maxDnevno = maxDnevno;
       this.poDanima = poDanima;
       this.galerijas = galerijas;
    }
   
    public String getNaziv() {
        return this.naziv;
    }
    
    public void setNaziv(String naziv) {
        this.naziv = naziv;
    }
    public Date getVremeOd() {
        return this.vremeOd;
    }
    
    public void setVremeOd(Date vremeOd) {
        this.vremeOd = vremeOd;
    }
    public Date getVremeDo() {
        return this.vremeDo;
    }
    
    public void setVremeDo(Date vremeDo) {
        this.vremeDo = vremeDo;
    }
    public String getMesto() {
        return this.mesto;
    }
    
    public void setMesto(String mesto) {
        this.mesto = mesto;
    }
    public int getBrUlaznica() {
        return this.brUlaznica;
    }
    
    public void setBrUlaznica(int brUlaznica) {
        this.brUlaznica = brUlaznica;
    }
    public int getCenaZaDan() {
        return this.cenaZaDan;
    }
    
    public void setCenaZaDan(int cenaZaDan) {
        this.cenaZaDan = cenaZaDan;
    }
    public int getCanaZaPaket() {
        return this.canaZaPaket;
    }
    
    public void setCanaZaPaket(int canaZaPaket) {
        this.canaZaPaket = canaZaPaket;
    }
    public int getOcena() {
        return this.ocena;
    }
    
    public void setOcena(int ocena) {
        this.ocena = ocena;
    }
    public int getMaxKarata() {
        return this.maxKarata;
    }
    
    public void setMaxKarata(int maxKarata) {
        this.maxKarata = maxKarata;
    }
    public int getMaxDnevno() {
        return this.maxDnevno;
    }
    
    public void setMaxDnevno(int maxDnevno) {
        this.maxDnevno = maxDnevno;
    }
    public String getPoDanima() {
        return this.poDanima;
    }
    
    public void setPoDanima(String poDanima) {
        this.poDanima = poDanima;
    }
    public Set<Galerija> getGalerijas() {
        return this.galerijas;
    }
    
    public void setGalerijas(Set<Galerija> galerijas) {
        this.galerijas = galerijas;
    }




}


