package bean;
// Generated 19-Feb-2017 19:06:23 by Hibernate Tools 4.3.1



/**
 * Galerija generated by hbm2java
 */
public class Galerija  implements java.io.Serializable {


     private Integer id;
     private Festival festival;
     private String naziv;
     private int vrsta;

    public Galerija() {
    }

    public Galerija(Festival festival, String naziv, int vrsta) {
       this.festival = festival;
       this.naziv = naziv;
       this.vrsta = vrsta;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Festival getFestival() {
        return this.festival;
    }
    
    public void setFestival(Festival festival) {
        this.festival = festival;
    }
    public String getNaziv() {
        return this.naziv;
    }
    
    public void setNaziv(String naziv) {
        this.naziv = naziv;
    }
    public int getVrsta() {
        return this.vrsta;
    }
    
    public void setVrsta(int vrsta) {
        this.vrsta = vrsta;
    }




}


