package bean;
// Generated 19-Feb-2017 19:06:23 by Hibernate Tools 4.3.1



/**
 * Komentari generated by hbm2java
 */
public class Komentari  implements java.io.Serializable {


     private String festival;
     private String username;
     private String komentar;

    public Komentari() {
    }

    public Komentari(String festival, String username, String komentar) {
       this.festival = festival;
       this.username = username;
       this.komentar = komentar;
    }
   
    public String getFestival() {
        return this.festival;
    }
    
    public void setFestival(String festival) {
        this.festival = festival;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getKomentar() {
        return this.komentar;
    }
    
    public void setKomentar(String komentar) {
        this.komentar = komentar;
    }




}


