package bean;
// Generated 19-Feb-2017 19:06:23 by Hibernate Tools 4.3.1



/**
 * Korisnik generated by hbm2java
 */
public class Korisnik  implements java.io.Serializable {


     private Integer id;
     private String ime;
     private String prezime;
     private String korisnickoIme;
     private String lozinka;
     private String telefon;
     private String email;
     private int tip;
     private int aktivan;

    public Korisnik() {
    }

    public Korisnik(String ime, String prezime, String korisnickoIme, String lozinka, String telefon, String email, int tip, int aktivan) {
       this.ime = ime;
       this.prezime = prezime;
       this.korisnickoIme = korisnickoIme;
       this.lozinka = lozinka;
       this.telefon = telefon;
       this.email = email;
       this.tip = tip;
       this.aktivan = aktivan;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getIme() {
        return this.ime;
    }
    
    public void setIme(String ime) {
        this.ime = ime;
    }
    public String getPrezime() {
        return this.prezime;
    }
    
    public void setPrezime(String prezime) {
        this.prezime = prezime;
    }
    public String getKorisnickoIme() {
        return this.korisnickoIme;
    }
    
    public void setKorisnickoIme(String korisnickoIme) {
        this.korisnickoIme = korisnickoIme;
    }
    public String getLozinka() {
        return this.lozinka;
    }
    
    public void setLozinka(String lozinka) {
        this.lozinka = lozinka;
    }
    public String getTelefon() {
        return this.telefon;
    }
    
    public void setTelefon(String telefon) {
        this.telefon = telefon;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public int getTip() {
        return this.tip;
    }
    
    public void setTip(int tip) {
        this.tip = tip;
    }
    public int getAktivan() {
        return this.aktivan;
    }
    
    public void setAktivan(int aktivan) {
        this.aktivan = aktivan;
    }




}


