package bean;
// Generated 19-Feb-2017 19:06:23 by Hibernate Tools 4.3.1



/**
 * Registracije generated by hbm2java
 */
public class Registracije  implements java.io.Serializable {


     private String korisnickoIme;
     private String ime;
     private String prezime;
     private String lozinka;
     private String telefon;
     private String email;

    public Registracije() {
    }

    public Registracije(String korisnickoIme, String ime, String prezime, String lozinka, String telefon, String email) {
       this.korisnickoIme = korisnickoIme;
       this.ime = ime;
       this.prezime = prezime;
       this.lozinka = lozinka;
       this.telefon = telefon;
       this.email = email;
    }
   
    public String getKorisnickoIme() {
        return this.korisnickoIme;
    }
    
    public void setKorisnickoIme(String korisnickoIme) {
        this.korisnickoIme = korisnickoIme;
    }
    public String getIme() {
        return this.ime;
    }
    
    public void setIme(String ime) {
        this.ime = ime;
    }
    public String getPrezime() {
        return this.prezime;
    }
    
    public void setPrezime(String prezime) {
        this.prezime = prezime;
    }
    public String getLozinka() {
        return this.lozinka;
    }
    
    public void setLozinka(String lozinka) {
        this.lozinka = lozinka;
    }
    public String getTelefon() {
        return this.telefon;
    }
    
    public void setTelefon(String telefon) {
        this.telefon = telefon;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }




}


