package bean;
// Generated 19-Feb-2017 19:06:23 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Rezervacije generated by hbm2java
 */
public class Rezervacije  implements java.io.Serializable {


     private Integer id;
     private String festival;
     private int brojUlaznica;
     private String korisnickoIme;
     private Date datum;
     private int paket;
     private int kupljeno;

    public Rezervacije() {
    }

    public Rezervacije(String festival, int brojUlaznica, String korisnickoIme, Date datum, int paket, int kupljeno) {
       this.festival = festival;
       this.brojUlaznica = brojUlaznica;
       this.korisnickoIme = korisnickoIme;
       this.datum = datum;
       this.paket = paket;
       this.kupljeno = kupljeno;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getFestival() {
        return this.festival;
    }
    
    public void setFestival(String festival) {
        this.festival = festival;
    }
    public int getBrojUlaznica() {
        return this.brojUlaznica;
    }
    
    public void setBrojUlaznica(int brojUlaznica) {
        this.brojUlaznica = brojUlaznica;
    }
    public String getKorisnickoIme() {
        return this.korisnickoIme;
    }
    
    public void setKorisnickoIme(String korisnickoIme) {
        this.korisnickoIme = korisnickoIme;
    }
    public Date getDatum() {
        return this.datum;
    }
    
    public void setDatum(Date datum) {
        this.datum = datum;
    }
    public int getPaket() {
        return this.paket;
    }
    
    public void setPaket(int paket) {
        this.paket = paket;
    }
    public int getKupljeno() {
        return this.kupljeno;
    }
    
    public void setKupljeno(int kupljeno) {
        this.kupljeno = kupljeno;
    }




}


